spring:
  application:
    name: library

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    baseName: i18n/messages
    local-default: en

spring-token:
  secret: kkkjgkhkd669$#65@#fghdfyhrtyerytryrtydfgjfg
  time: 1h


server:
  port: 8080
